[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
contriearn_escrow = "4xMcXKdwTsSrdTKoZBc59dUwpKeCfZyf7DGaMDi8x8Gp"

[programs.localnet]
contriearn_escrow = "4xMcXKdwTsSrdTKoZBc59dUwpKeCfZyf7DGaMDi8x8Gp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
